### PR TITLE
Add guess the number game

### PR DESCRIPTION
**Pull request by retrouser955**
## Changes
describe what changes this PR includes and explain why are they needed

## Screenshots
If applicable, add screenshots to explain the change.

## Status

- [x] These changes have been tested and formatted properly.
- [x] These changes also include the change in documentation accordingly.
- [ ] This PR introduces some Breaking changes

### CODE REVIEW

**Comment by rishanbenahalkar** [comment]
👍🏻 coolio

**Comment by ChrisSch-dev** [comment]
One thing caught my attention, why is a yarn.lock file added?

**Comment by retrouser955** [comment]
> One thing caught my attention, why is a yarn.lock file added?

Tbh, I have no idea 😂. I always add it to all my projects. I can remove it if Aniket say so.

**Comment by rishanbenahalkar** [comment]
This pull request probably won't be merged until the new bug fix update is published.

**Comment by retrouser955** [comment]
Yes, the owner of the repo (Aniket) have told me in discord about this.

**Comment by ChrisSch-dev** [comment]
> > One thing caught my attention, why is a yarn.lock file added?
> 
> Tbh, I have no idea 😂. I always add it to all my projects. I can remove it if Aniket say so.

You should probably remove the `yarn.lock` then. It isn't necessary here, and it may cause some issue.

**Review by ChrisSch-dev — CHANGES_REQUESTED** [review]
remove `yarn.lock`

**Comment by retrouser955** [comment]
I just read. `yarn.lock` provide yarn on the information about dependencies of the project and tell yarn how to manage the project. The [post](https://stackoverflow.com/questions/39990017/should-i-commit-the-yarn-lock-file-and-what-is-it-for) states that, if you do not push `lock` files (package-lock.json, yarn.lock), it could cause issues on other machines. Thus, I will be keeping this file for now and I will remove it when the pull request is getting close to merging.

**Comment by retrouser955** [comment]
Oh 😅 I didn't realise the pull request was open haha. I was just clearing out repos that I am inactive on.

**Pull request closed without merging**
